# This is a basic workflow to help you get started with Actions

name: CD

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./demo

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build App
        run: ./gradlew bootJar

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST1 }}
          key: ${{ secrets.PRIVATE_KEY1 }}
          source: "./demo/build/libs/*.jar"
          target: "/home/ubuntu/deploy"
          strip_components: 3

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST1 }}
          key: ${{ secrets.PRIVATE_KEY1 }}
          script: |
            echo sudo -S /home/ubuntu/deploy/deploy.sh
